### PR TITLE
Change to require platformdirs instead of appdirs

### PR DESCRIPTION
**Pull request by adybbroe**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adybbroe** [comment]
@conda-forge-admin, please rerender

**Review by djhoese — APPROVED** [review]

**Comment by djhoese** [comment]
@adybbroe this commit needs to be done on the version update PR. Otherwise this is invalid as the existing version doesn't use platformdirs.

**Review by djhoese — CHANGES_REQUESTED** [review]
As mentioned, I'm not sure this main branch version if pyspectral uses platformdirs. The change to platformdirs needs to modify the bot's PR.

**Comment by adybbroe** [comment]
> As mentioned, I'm not sure this main branch version if pyspectral uses platformdirs. The change to platformdirs needs to modify the bot's PR.

But once main is updated I can merge main into the bot's PR, that was my intention...

**Comment by djhoese** [comment]
Right. The goal is to not put a build of the package out into the world that is incorrect. Since `main` is automatically built and released and you have permissions to modify the bot's PR then it makes the most sense to do these changes in the bot's PR. Put another, the bot's PR is currently incorrect. It needs to be fixed.

And I see you've done that.

**Pull request closed without merging**
